In [1]:
import numpy as np

In [2]:
np.eye(3)#matriz de identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.full((5,2),7)

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [8]:
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
S=3

print(M*S)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
