In [14]:
import numpy as np

In [15]:
M1 =np.round( np.random.randn(4,5))
M2 =np.round(np.random.randn(4,5))

print( np.matmul(M1,M2.T))#para sumar matrices

[[-1.  0. -2. -2.]
 [ 3. -1.  2.  2.]
 [ 0.  2. -2. -3.]
 [-2.  1.  0.  2.]]


In [16]:
print(M1@M2.T)#para sumar matrices mas facil sin np
print(' ')
print( np.matmul(M1,M2.T) - (M1@M2.T))

[[-1.  0. -2. -2.]
 [ 3. -1.  2.  2.]
 [ 0.  2. -2. -3.]
 [-2.  1.  0.  2.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
