In [2]:
import numpy as np

In [7]:
v1 = np.array([2,3,-1],ndmin=2)

print(v1)
print(v1.T)

[[ 2  3 -1]]
[[ 2]
 [ 3]
 [-1]]


In [14]:
M = np.round(10*np.random.randn(3,3))
print(M)
print(' ')
print(M.T)


[[10.  4. -4.]
 [18. 14. -7.]
 [-5. 11. 10.]]
 
[[10. 18. -5.]
 [ 4. 14. 11.]
 [-4. -7. 10.]]


In [16]:
M = np.round(10*np.random.randn(3,2))
N= M.T
print(M)
print(' ')
print(N)
print(' ')
print(N.T)

[[  6.  -3.]
 [  1.  -6.]
 [ -0. -17.]]
 
[[  6.   1.  -0.]
 [ -3.  -6. -17.]]
 
[[  6.  -3.]
 [  1.  -6.]
 [ -0. -17.]]
